In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [77]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/cleveland.csv')
df.head()

age  sex  cp  trestbps  chol  fps  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

    ca  thal  target  
0  0.0   6.0       0  
1  3.0   3.0       2  
2  2.0   7.0       1  
3  0.0   3.0       0  
4  0.0   3.0       0

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fps       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        299 non-null    float64
 12  thal      301 non-null    float64
 13  target    303 non-null    int64  
dtypes: float64(3), int64(11)
memory usage: 33.3 KB


In [79]:
dnull = df[df.isnull().any(axis=1)]
dnull

age  sex  cp  trestbps  chol  fps  restecg  thalach  exang  oldpeak  \
87    53    0   3       128   216    0        2      115      0      0.0   
166   52    1   3       138   223    0        0      169      0      0.0   
192   43    1   4       132   247    1        2      143      1      0.1   
266   52    1   4       128   204    1        0      156      1      1.0   
287   58    1   2       125   220    0        0      144      0      0.4   
302   38    1   3       138   175    0        0      173      0      0.0   

     slope   ca  thal  target  
87       1  0.0   NaN       0  
166      1  NaN   3.0       0  
192      2  NaN   7.0       1  
266      2  0.0   NaN       2  
287      2  NaN   7.0       0  
302      1  NaN   3.0       0

In [80]:
for i in range(df.shape[0]):
  if pd.isnull(df.loc[i,'ca']):
    cvalue = df.loc[i,'target']
    df.loc[i,'ca'] = df[df['target'] == cvalue].mode().iloc[0,11]

In [81]:
df.tail()

age  sex  cp  trestbps  chol  fps  restecg  thalach  exang  oldpeak  \
298   45    1   1       110   264    0        0      132      0      1.2   
299   68    1   4       144   193    1        0      141      0      3.4   
300   57    1   4       130   131    0        0      115      1      1.2   
301   57    0   2       130   236    0        2      174      0      0.0   
302   38    1   3       138   175    0        0      173      0      0.0   

     slope   ca  thal  target  
298      2  0.0   7.0       1  
299      2  2.0   7.0       2  
300      2  1.0   7.0       3  
301      2  1.0   3.0       1  
302      1  0.0   3.0       0

In [92]:
df = df.dropna()
df

age  sex  cp  trestbps  chol  fps  restecg  thalach  exang  oldpeak  \
0     63    1   1       145   233    1        2      150      0      2.3   
1     67    1   4       160   286    0        2      108      1      1.5   
2     67    1   4       120   229    0        2      129      1      2.6   
3     37    1   3       130   250    0        0      187      0      3.5   
4     41    0   2       130   204    0        2      172      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   45    1   1       110   264    0        0      132      0      1.2   
299   68    1   4       144   193    1        0      141      0      3.4   
300   57    1   4       130   131    0        0      115      1      1.2   
301   57    0   2       130   236    0        2      174      0      0.0   
302   38    1   3       138   175    0        0      173      0      0.0   

     slope   ca  thal  target  
0        3  0.0   6.0       0  
1        2  3.0   3.0       2  
2        2  2.0   7.0       1  
3        3  0.0   3.0       0  
4        1  0.0   3.0       0  
..     ...  ...   ...     ...  
298      2  0.0   7.0       1  
299      2  2.0   7.0       2  
300      2  1.0   7.0       3  
301      2  1.0   3.0       1  
302      1  0.0   3.0       0  

[301 rows x 14 columns]

In [150]:
import numpy as np

X = df.iloc[:,:-1]
y = df.iloc[:,-1]
X = np.array(X)
X

array([[63.,  1.,  1., ...,  3.,  0.,  6.],
       [67.,  1.,  4., ...,  2.,  3.,  3.],
       [67.,  1.,  4., ...,  2.,  2.,  7.],
       ...,
       [57.,  1.,  4., ...,  2.,  1.,  7.],
       [57.,  0.,  2., ...,  2.,  1.,  3.],
       [38.,  1.,  3., ...,  1.,  0.,  3.]])

In [151]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(X)

array([[ 0.94432161,  0.68431914, -2.2449357 , ...,  2.27113463,
        -0.7146918 ,  0.65364997],
       [ 1.38620393,  0.68431914,  0.87860349, ...,  0.64735429,
         2.49608777, -0.89555192],
       [ 1.38620393,  0.68431914,  0.87860349, ...,  0.64735429,
         1.42582791,  1.1700506 ],
       ...,
       [ 0.28149812,  0.68431914,  0.87860349, ...,  0.64735429,
         0.35556806,  1.1700506 ],
       [ 0.28149812, -1.46130649, -1.20375597, ...,  0.64735429,
         0.35556806, -0.89555192],
       [-1.81744291,  0.68431914, -0.16257624, ..., -0.97642605,
        -0.7146918 , -0.89555192]])

In [152]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,stratify=y, random_state=42)

In [153]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [154]:
classifier = KNeighborsClassifier(n_neighbors=5, algorithm='kd_tree')
classifier.fit(X_train, y_train).score(X_test, y_test)

0.5081967213114754

In [155]:
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train).score(X_test, y_test)

0.5245901639344263

In [156]:
# n_neighbors=5, weights='distance', algorithm='auto'
estimators = [('knn', KNeighborsClassifier()),
              ('nb', GaussianNB()),
              ('dt', DecisionTreeClassifier(random_state=42)),
              ('rf', RandomForestClassifier(random_state=42)),
              ('ada', AdaBoostClassifier(random_state=42)),
              ('svc', SVC(kernel='rbf', random_state=42)),
              ('gb', GradientBoostingClassifier(random_state=42))]

clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())
clf.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


StackingClassifier(estimators=[('knn', KNeighborsClassifier()),
                               ('nb', GaussianNB()),
                               ('dt', DecisionTreeClassifier(random_state=42)),
                               ('rf', RandomForestClassifier(random_state=42)),
                               ('ada', AdaBoostClassifier(random_state=42)),
                               ('svc', SVC(random_state=42)),
                               ('gb',
                                GradientBoostingClassifier(random_state=42))],
                   final_estimator=LogisticRegression())

In [157]:
y_preds = clf.predict(X_test)
print(confusion_matrix(y_preds, y_test))
print(accuracy_score(y_test, y_preds))
print(y_preds)

[[33  7  2  0  0]
 [ 0  0  0  0  0]
 [ 0  2  4  7  0]
 [ 0  2  1  0  3]
 [ 0  0  0  0  0]]
0.6065573770491803
[0 0 0 0 0 0 0 0 2 0 3 0 0 2 3 3 3 0 3 3 0 0 0 0 0 0 0 2 0 2 0 0 2 0 0 0 0
 2 0 0 0 2 2 0 0 0 0 0 2 0 0 0 0 0 0 2 2 2 0 0 2]
